import 'package:get/get.dart';

class PtBr extends Translations {
  @override
  Map<String, Map<String, String>> get keys => const {
    'pt_BR': ptBr,
  };
}

const Map<String, String> ptBr = {
  'home': 'Início',
  'cart': 'Carrinho',
  'menu': 'Cardápio',
  'favourite': 'Favoritos',
  'quantity': 'Quantidade',
  'addons': 'Adicionais',
  'items': 'Itens',
  'item': 'Item',
  'add_to_cart': 'Adicionar ao carrinho',
  'checkout': 'Finalizar pedido',
  'delivery_address': 'Endereço de entrega',
  'add': 'Adicionar',
  'payment_method': 'Forma de pagamento',
  'cash_on_delivery': 'Pagamento na entrega',
  'digital_payment': 'Pagamento digital',
  'debit_or_credit_card_payment': 'Pagamento com cartão de débito ou crédito',
  'confirm_order': 'Confirmar pedido',
  'order_tracking': 'Acompanhar pedido',
  'order_details': 'Detalhes do pedido',
  'search_items_here': 'Digite algo e pressione enter...',
  'all_categories': 'Todas as categorias',
  'view_all': 'Ver tudo',
  'popular_item': 'Itens populares',
  'banner': 'Banner',
  'set_menu': 'Menu do dia',
  'delivery_man': 'Entregador',
  'order_accepted': 'Pedido aceito',
  'preparing_food': 'Preparando o pedido',
  'food_in_the_way': 'Pedido a caminho',
  'delivered_the_food': 'Pedido entregue',
  'view_in_map': 'Ver no mapa',
  'order_complete': 'Pedido concluído',
  'profile': 'Perfil',
  'message': 'Mensagem',
  'coupon': 'Cupom',
  'my_order': 'Meus pedidos',
  'language': 'Idioma',
  'logout': 'Sair',
  'type_message_here': 'Digite a mensagem aqui ...',
  'choose_the_language': 'Escolha o idioma',
  'find_language': 'Buscar idioma',
  'english': 'Inglês',
  'germany': 'Alemão',
  'korean': 'Coreano',
  'italian': 'Italiano',
  'chinese': 'Chinês',
  'japanese': 'Japonês',
  'arabic': 'Árabe',
  'save': 'Salvar',
  'make_your_choice_order': 'Faça sua escolha e peça',
  'select_delivery_location': 'Selecione o local de entrega',
  'delivery_to_your_home': 'Entrega em sua casa',
  'lorem__ant': 'Lorem ipsum dolor sit amet, conse te sadipscing elitr, sed diam ant',
  'skip': 'Pular',
  'lets_start': 'Vamos começar',
  'next': 'Próximo',
  'previous': 'Anterior',
  'welcome': 'Bem-vindo',
  'login': 'Entrar',
  'signup': 'Cadastre-se',
  'email': 'E-mail',
  'demo_gmail': 'demo@gmail.com',
  'password_did_not_match': 'As senhas não coincidem',
  'mobile_number': 'Número de celular',
  'number_hint': '1234567890',
  'password': 'Senha',
  'password_hint': '••••••••••',
  'remember_me': 'Lembrar de mim',
  'create_an_account': 'Criar uma conta',
  'already_have_account': 'Já possui uma conta?',
  'continue': 'Continuar',
  'forgot_password': 'Esqueceu sua senha?',
  'confirm_password': 'Confirmar senha',
  'enter_the_code': 'Insira o código',
  'enter_the_code__fill_it': 'Insira o código que enviamos para o seu telefone, por favor verifique e preencha.',
  'i_didnt_receive_the_code': 'Não recebi o código ',
  'resend_code': 'REENVIAR CÓDIGO',
  'verified': 'Verificado',
  'create_account': 'Criar conta',
  'first_name': 'Nome',
  'mehedi_hasan': 'Mehedi Hasan',
  'last_name': 'Sobrenome',
  'mamun': 'Mamun',
  'select_location': 'Selecionar local',
  'select_delivery_address': 'Selecionar endereço de entrega',
  'search_location_here': 'Buscar localização aqui...',
  'my_cart': 'Meu carrinho',
  'enter_promo_code': 'Inserir código promocional',
  'apply': 'Aplicar',
  'subtotal': 'Subtotal',
  'delivery_fee': 'Taxa de Entrega',
  'total_amount': 'Valor Total',
  'place_order': 'Finalizar Pedido',
  'no_data_available': 'Nenhum dado disponível',
  'order_placed_successfully': 'Pedido realizado com sucesso',
  'order_id': 'ID do Pedido',
  'order_more': 'Pedir mais',
  'running': 'Em andamento',
  'history': 'Histórico',
  'cancel_order': 'Cancelar Pedido',
  'reorder': 'Pedir novamente',
  'details': 'Detalhes',
  'track_order': 'Acompanhar Pedido',
  'my_profile': 'Meu Perfil',
  'workplace': 'Trabalho',
  'add_new_address': 'Adicionar Novo Endereço',
  'update_address': 'Atualizar Endereço',
  'add_the_location_correctly': 'Adicione o local corretamente',
  'address_line_01': 'Endereço',
  'address_line_02': '23/A Bloco, Setor 4',
  'label_us': 'Identificar como',
  'other': 'Outros',
  'save_location': 'Salvar Local',
  'contact_person_name': 'Nome do contato',
  'enter_contact_person_name': 'Digite o nome do contato',
  'contact_person_number': 'Número do contato',
  'enter_contact_person_number': 'Digite o número do contato',
  'description': 'Descrição',
  'added_to_cart': 'Adicionado ao carrinho',
  'delivered_at': 'Entregue em',
  'edit': 'Editar',
  'delete': 'Excluir',
  'notification': 'Notificação',
  'please_enter_your_number_to': 'Por favor, insira seu endereço de e-mail para \nreceber um código de verificação.',
  'send': 'Enviar',
  'verify_email': 'Verificar E-mail',
  'verify_phone': 'Verificar Telefone',
  'please_enter_4_digit_code': 'Por favor, insira o código de 4 dígitos enviado para ',
  'verify': 'Verificar',
  'create_new_password': 'Criar Nova Senha',
  'enter_password_to_create': 'Insira a senha para criar sua \nnova senha',
  'new_password': 'Nova Senha',
  'my_favourite': 'Favoritos',
  'rate_review': 'Avaliar e Comentar',
  'rate_the_food': 'Avalie a Comida',
  'share_your_opinion': 'Compartilhe sua opinião',
  'write_your_review_here': 'Escreva sua avaliação aqui . . .',
  'submit': 'Enviar',
  'thanks_for_your_order': 'Obrigado pelo seu pedido',
  'it_will_helps_to_improve': 'Isso nos ajudará a melhorar a\nqualidade do nosso serviço',
  'back_home': 'Voltar para o Início',
  'update_profile': 'Atualizar Perfil',
  'coupon_discount': 'Desconto do Cupom',
  'valid_until': 'Válido até',
  'order': 'Pedido',
  'cancel': 'Cancelar',
  'recent_search': 'Pesquisas recentes',
  'remove_all': 'Remover tudo',
  'product_found': 'produtos encontrados',
  'price': 'Preço',
  'filter': 'Filtro',
  'reset': 'Redefinir',
  'rating': 'Avaliação',
  'category': 'Categoria',
  'review': 'Avaliar',
  'tax': 'Imposto/Taxa',
  'discount': 'Desconto',
  'coupon_code_copied': 'Código do cupom copiado',
  'dark_theme': 'Tema escuro',
  'payment_cancelled': 'Pagamento cancelado',
  'order_failed': 'Falha no pedido',
  'PAYMENT': 'PAGAMENTO',
  'no_order_history_available': 'Nenhum pedido disponível',
  'buy_something_to_see': 'Compre algo para ver seu pedido aqui.',
  'empty_cart': 'Carrinho vazio',
  'look_like_have_not_added': 'Parece que você ainda não adicionou nenhum item',
  'nothing_found': 'Nada encontrado',
  'sorry_the_products_you_looking': 'Desculpe, os produtos que você está procurando não existem ou não foram encontrados',
  'order_placed': 'Pedido realizado',
  'pay_now': 'Pagar agora',
  'yes': 'Sim',
  'no': 'Não',
  'are_you_sure_to_cancel': 'Tem certeza de que deseja cancelar este pedido?',
  'want_to_sign_out': 'Tem certeza de que deseja sair?',
  'address': 'Endereço',
  'already_added_in_cart': 'Já adicionado ao carrinho',
  'payment_failed': 'Falha no pagamento',
  'payment_process_is_interrupted': 'O processo de pagamento foi interrompido. Por favor, conclua o pagamento do pedido na página de detalhes do pedido.',
  'maybe_later': 'Talvez depois',
  'ordered_at': 'Pedido feito em',
  'you_can_choice_the_best': 'Você pode escolher a melhor comida para saciar sua fome.',
  'select_accurate_location': 'Selecione a localização precisa no Google Maps e receba sua comida na sua porta.',
  'get_food_delivery_at_home': 'Receba comida em casa, pague online e aproveite.',
  'welcome_to_efood': 'Bem-vindo ao eFood, por favor, faça login ou cadastre-se para continuar.',
  'no_category_available': 'Nenhuma categoria disponível',
  'no_set_menu_available': 'Nenhum menu fixo disponível',
  'no_banner_available': 'Nenhum banner disponível',
  'restaurant_is_close_now': 'O restaurante está fechado agora',
  'not_available_now_break': 'Indisponível\nagora',
  'not_available_now': 'Não disponível agora',
  'available_will_be': 'Estará disponível',
  'additional_note': 'Observação adicional',
  'terms_and_condition': 'Termos e Condições',
  'help_and_support': 'Ajuda e Suporte',
  'restaurant_address': 'Endereço do Restaurante:',
  'call_now': 'Ligar agora',
  'send_a_message': 'Enviar uma mensagem',
  'no_terms_and_condition': 'Sem termos e condições',
  'items_price': 'Preço dos itens',
  'order_cancelled': 'Pedido cancelado',
  'no_connection': 'Sem conexão',
  'connected': 'Conectado',
  'payment_info': 'Informações de pagamento',
  'status': 'Status:',
  'method': 'Método:',
  'change': 'Alterar',
  'do_you_want_to_switch': 'Deseja alterar seu método de pagamento de Pagamento Digital para Pagamento na Entrega?',
  'service_is_not_available': 'Serviço não está disponível nesta área.',
  'submitted': 'Enviado',
  'rate_his_service': 'Avalie o serviço',
  'update_in_cart': 'Atualizar no carrinho',
  'updated_in_cart': 'Atualizado no carrinho',
  'delivery': 'Entrega em domicílio',
  'take_away': 'Retirada',
  'invalid_code_or': 'Código inválido ou falha ao obter desconto',
  'one_or_more_product_unavailable': 'Um ou mais produtos no seu carrinho não estão disponíveis no momento',
  'no_address_available': 'Nenhum endereço disponível',
  'select_an_address': 'Selecione um endereço',
  'change_something_to_update': 'Altere algo para atualizar',
  'updated_successfully': 'Atualizado com sucesso',
  'password_should_be': 'A senha deve ter 6 ou mais caracteres',
  'no_delivery_man_data_found': 'Dados de localização do entregador não encontrados',
  'delivery_option': 'Opção de entrega',
  'free': 'Grátis',
  'select_branch': 'Selecione a filial',
  'out_of_coverage_for_this_branch': 'Este endereço está fora da área de cobertura \npara esta filial',
  'select_a_language': 'Selecione um idioma',
  'enter_a_Coupon_code': 'Digite um código de cupom',
  'enter_email_address': 'Digite o endereço de e-mail',
  'enter_password': 'Digite a senha',
  'enter_confirm_password': 'Confirme sua senha',
  'enter_valid_email': 'Digite um e-mail válido',
  'enter_phone_number': 'Digite o número de telefone',
  'enter_first_name': 'Digite o nome',
  'enter_last_name': 'Digite o sobrenome',
  'guest': 'Usuário Convidado',
  'login_as_a': 'Entrar como',
  'now_you_are_in_guest_mode': 'Agora você está no modo de convidado.\nFaça login para aproveitar recursos mais incríveis.',
  'guest_mode': 'Modo de Convidado',
  'you_have_to_allow': 'Você precisa permitir o acesso à localização para adicionar um novo endereço',
  'you_denied_location_permission': 'Você negou a permissão de localização permanentemente. Você precisa permitir o acesso à localização para adicionar um novo endereço.',
  'privacy_policy': 'Política de Privacidade',
  'about_us': 'Sobre Nós',
  'ok': 'OK',
  'notifications': 'Notificações',
  'no_data_found': 'Nenhum dado encontrado',
  'necessary_links': 'Links Necessários',
  'pending': 'Pendente',
  'confirmed': 'Confirmado',
  'processing': 'Em processamento',
  'out_for_delivery': 'Saiu para entrega',
  'delivered': 'Entregue',
  'returned': 'Devolvido',
  'failed': 'Falhou',
  'canceled': 'Cancelado',
  'paid': 'Pago',
  'unpaid': 'Não pago',
  'preference_time': 'Horário de preferência',
  'today': 'Hoje',
  'tomorrow': 'Amanhã',
  'now': 'Agora',
  'no_slot_available': 'Nenhum horário disponível',
  'select_a_time': 'Selecione um horário',
  'one_or_more_products_are_not_available_for_this_selected_time': 'Um ou mais produtos não estão disponíveis para este horário selecionado',
  'points': 'Pontos',
  'please_enter_your_mobile_number_to': 'Por favor, digite seu número de celular para \nreceber um código de verificação.',
  'maintenance_mode': 'Modo de Manutenção',
  'maintenance_text': 'Estamos realizando uma manutenção agendada. Voltaremos o mais breve possível. Por favor, verifique novamente em breve.',
  'self_pickup_not_available': 'Retirada no local indisponível',
  'home_delivery_not_available': 'Entrega em domicílio indisponível',
  'search_location': 'Buscar localização...',
  'will_add_later': 'Adicionarei depois',
  'not_found': 'Não encontrado',
  'delivery_fee_not_set_yet': 'Taxa de entrega ainda não definida',
  'continue_checkout': 'Continuar para o pagamento',
  'failed_to_fetch_distance': 'Falha ao calcular a distância',
  'delivery_fee_from_your_selected_address_to_branch': 'Taxa de entrega do seu endereço selecionado até a filial',
  'version007': 'version007',
  'chat_with_delivery_man': 'Conversar com o entregador',
  'admin': 'Administrador',
  'write_something': 'Escreva algo',
  'please_check_internet_connection': 'Por favor, verifique sua conexão com a internet',
  'page_not_found': 'Página não encontrada',
  'customer_not_found': 'Cliente não encontrado!',
  'off': 'DESATIVADO',
  'on': 'ATIVADO',
  'dark_mode': 'Modo Escuro',
  'see_more': 'Ver mais',
  'quick_view': 'Visualização rápida',
  'subscribe_to_our': 'Assine nossa newsletter para receber as últimas atualizações',
  'your_email_address': 'Seu endereço de e-mail',
  'follow_us_on': 'Siga-nos em',
  'download_our_app': 'BAIXE NOSSO APLICATIVO',
  'download_our_apps': 'BAIXE NOSSOS APLICATIVOS',
  'quick_links': 'Links rápidos',
  'contact_us': 'Fale conosco',
  'live_chat': 'Chat ao vivo',
  'news_letter': 'NEWSLETTER',
  'subscribe': 'Inscrever-se',
  'search': 'Buscar......',
  'successfully_subscribe': 'Inscrição realizada com sucesso',
  'add_new': 'Adicionar novo',
  'write_somethings': 'Escreva algo',
  'mail_already_exist': 'E-mail já existe',
  'copyright': 'Direitos autorais © 2022',
  'my_account': 'Minha conta',
  'want_to_delete': 'Tem certeza que deseja excluir o endereço?',
  'your_app_is_deprecated': 'O aplicativo que você está usando está obsoleto. Uma versão mais recente deste aplicativo está disponível. Por favor, atualize seu aplicativo.',
  'update_now': 'Atualizar agora',
  'can_not_launch': 'Não foi possível abrir',
  'version': 'Versão',
  'extra_discount': 'Desconto extra',
  'address_not_found': 'Endereço não encontrado',
  'cash_on_delivery_is_not_activated': 'Pagamento na entrega não está ativado',
  'payment_method_is_not_activated_please_order_later': 'Método de pagamento não ativado, por favor realize o pedido mais tarde',
  'pos_order': 'Pedido POS',
  'self_pickup': 'Retirada',
  'variation': 'Variação',
  'food_preparation_time': 'Tempo de preparo: ',
  'day': 'Dia',
  'hour': 'Hora',
  'min': 'Min',
  'sec': 'Seg',
  'to': 'até',
  'latest_item': 'Últimos itens',
  'your_food_delivery': 'Sua entrega chegará em',
  'be_prepared_your_food': 'Prepare-se, sua comida chegará a qualquer momento',
  'your_account_remove_successfully': 'Sua conta foi removida com sucesso',
  'there_is_a_problem_on_removing_your_account': 'Houve um problema ao remover sua conta',
  'delete_account': 'Excluir conta',
  'are_you_sure_to_delete_account': 'Tem certeza que deseja excluir sua conta?',
  'it_will_remove_your_all_information': 'Isso removerá todas as suas informações.',
  'return_policy': 'Política de devolução',
  'refund_policy': 'Política de reembolso',
  'cancellation_policy': 'Política de cancelamento',
  'user_not_available': 'Usuário indisponível',
  'review_submitted_successfully': 'Avaliação enviada com sucesso',
  'all': 'Todos',
  'non_veg': 'Não vegetariano',
  'veg': 'Vegetariano',
  'show_less': 'Mostrar menos',
  'show_more': 'Mostrar mais',
  'dine_in': 'Consumo no local',
};
